/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package modifikasi;

import bridging.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import java.awt.Dimension;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.net.URI;
import java.security.SecureRandom;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.net.ssl.SSLContext;
import javax.net.ssl.X509TrustManager;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import org.apache.http.client.methods.HttpEntityEnclosingRequestBase;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.conn.scheme.Scheme;
import org.apache.http.conn.ssl.SSLSocketFactory;
import org.junit.Test;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author dosen
 */
public final class BPJSListRujukanKeluarKhusus extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private validasi Valid=new validasi();
    private sekuel Sequel=new sekuel();
    private int i=0,row=0;
    private ApiBPJS api=new ApiBPJS();
    private String URL="",link="",utc="",requestJson="", user="",URL2="",link2="",requestJson2="";
    private HttpHeaders headers;
    private HttpEntity requestEntity;
    private ObjectMapper mapper = new ObjectMapper();
    private ObjectMapper mapper2 = new ObjectMapper();
    private JsonNode root,root2;
    private JsonNode nameNode,nameNode2;
    private JsonNode response,response2;
    private Properties prop = new Properties();

    /** Creates new form DlgKamar
     * @param parent
     * @param modal */
    public BPJSListRujukanKeluarKhusus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(628,674);

        tabMode = new DefaultTableModel(null, new String[]{"Id Rujukan", "No.Rujukan","No. Kartu", "Nama Pasien", "Diagnosa",
            "Tgl. Rujukan ","Tgl. Berakhir Rujukan"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbKamar.setModel(tabMode);

        //tbKamar.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbKamar.getBackground()));
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 7; i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(150);
            } else if (i == 1) {
                column.setPreferredWidth(150);
            } else if (i == 2) {
                column.setPreferredWidth(100);
            } else {
                column.setPreferredWidth(100);
            }
        }
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());
        
  
        
        try {
            user=akses.getkode().replace(" ","").substring(0,9);
        } catch (Exception e) {
            user=akses.getkode();
        }
        
        try {
            link=koneksiDB.URLAPIBPJS();
            link2=koneksiDB.URLAPIBPJS();
        } catch (Exception e) {
            System.out.println("E : "+e);
        }
        
        
        Valid.LoadTahun(Tahun);
              
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnTampilkanData = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelGlass6 = new widget.panelisi();
        jLabel17 = new widget.Label();
        label11 = new widget.Label();
        Tahun = new widget.ComboBox();
        Bulan = new widget.ComboBox();
        jLabel16 = new widget.Label();
        Tcari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnSimpan = new widget.Button();
        BtnKeluar = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(192, 24));

        MnTampilkanData.setBackground(new java.awt.Color(255, 255, 254));
        MnTampilkanData.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnTampilkanData.setForeground(java.awt.Color.darkGray);
        MnTampilkanData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnTampilkanData.setText("Tampil Data Terbaru");
        MnTampilkanData.setName("MnTampilkanData"); // NOI18N
        MnTampilkanData.setPreferredSize(new java.awt.Dimension(170, 28));
        MnTampilkanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTampilkanDataActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnTampilkanData);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ List Rujukan Khusus BPJS ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);
        Scroll.setPreferredSize(new java.awt.Dimension(452, 452));

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setComponentPopupMenu(jPopupMenu1);
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass6.add(jLabel17);

        label11.setText("Tahun & Bulan :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(110, 23));
        panelGlass6.add(label11);

        Tahun.setName("Tahun"); // NOI18N
        Tahun.setPreferredSize(new java.awt.Dimension(80, 23));
        panelGlass6.add(Tahun);

        Bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        Bulan.setName("Bulan"); // NOI18N
        Bulan.setPreferredSize(new java.awt.Dimension(62, 23));
        panelGlass6.add(Bulan);

        jLabel16.setText("Keyword :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(110, 23));
        panelGlass6.add(jLabel16);

        Tcari.setName("Tcari"); // NOI18N
        Tcari.setPreferredSize(new java.awt.Dimension(200, 23));
        Tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcariActionPerformed(evt);
            }
        });
        Tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TcariKeyPressed(evt);
            }
        });
        panelGlass6.add(Tcari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnSimpan);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass6.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass6.add(LCount);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnCari,BtnKeluar);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
//            Valid.pindah(evt,NoKaBPJS,BtnPrint);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        tampildata(Tahun.getSelectedItem().toString(),Bulan.getSelectedItem().toString(), Tcari.getText());
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnCariActionPerformed

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if(tabMode.getRowCount()!=0){
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
    }//GEN-LAST:event_tbKamarMouseClicked

    private void TcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcariActionPerformed

    private void TcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TcariKeyPressed

    }//GEN-LAST:event_TcariKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Maaf, data pada tabel masih kosong ...!");
        } else {
                try {
                    for(int i=0; i<tbKamar.getRowCount(); i++){
                        String noRujukan = tbKamar.getValueAt(i,1).toString();
                        String kdDiagnosa = tbKamar.getValueAt(i,4).toString();
                        String tglAwal = tbKamar.getValueAt(i,5).toString();
                        String tglAkhir = tbKamar.getValueAt(i,6).toString();
                        String nmDiagnosa = Sequel.cariIsi("SELECT nm_penyakit FROM penyakit WHERE kd_penyakit='"+kdDiagnosa+"'");

                        // === CEK APAKAH DATA SUDAH ADA DI bridging_rujukan_bpjs_khusus ===
                        if(Sequel.cariInteger("SELECT COUNT(*) FROM bridging_rujukan_bpjs_khusus WHERE no_rujukan='"+noRujukan+"'") == 0){
                            // Belum ada → INSERT
                            Sequel.menyimpan(
                                "bridging_rujukan_bpjs_khusus",
                                "?,?,?,?,?",
                                5,
                                new String[]{
                                    noRujukan,
                                    tbKamar.getValueAt(i,2).toString(),
                                    tbKamar.getValueAt(i,3).toString(),
                                    tglAwal,
                                    tglAkhir
                                }
                            );
                        } else {
                            // Sudah ada → UPDATE
                            Sequel.mengedit(
                                "bridging_rujukan_bpjs_khusus",
                                "no_rujukan=?",
                                "tglrujukan_awal='"+tglAwal+"', tglrujukan_berakhir='"+tglAkhir+"'",
                                1,
                                new String[]{ noRujukan }
                            );
                        }

                        // === UNTUK TABEL DIAGNOSA ===
                        if(Sequel.cariInteger("SELECT COUNT(*) FROM bridging_rujukan_bpjs_khusus_diagnosa WHERE no_rujukan='"+noRujukan+"'") == 0){
                            Sequel.menyimpan(
                                "bridging_rujukan_bpjs_khusus_diagnosa",
                                "?,?,?,?",
                                4,
                                new String[]{
                                    noRujukan,
                                    "P",
                                    kdDiagnosa,
                                    nmDiagnosa
                                }
                            );
                        } else {
                            Sequel.mengedit(
                                "bridging_rujukan_bpjs_khusus_diagnosa",
                                "no_rujukan=?",
                                "kode_diagnosa='"+kdDiagnosa+"', nama_diagnosa='"+nmDiagnosa+"'",
                                1,
                                new String[]{ noRujukan }
                            );
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan/diupdate!");
                } catch (Exception ex) {
                    System.out.println("Notifikasi error: "+ex);
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data!");
                }
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,BtnCari,BtnKeluar);
        }
    }//GEN-LAST:event_BtnSimpanKeyPressed

    private void MnTampilkanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTampilkanDataActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            tampildataYangBelumAda(Tahun.getSelectedItem().toString(),Bulan.getSelectedItem().toString(), Tcari.getText());
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_MnTampilkanDataActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            BPJSListRujukanKeluarKhusus dialog = new BPJSListRujukanKeluarKhusus(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.ComboBox Bulan;
    private widget.Label LCount;
    private javax.swing.JMenuItem MnTampilkanData;
    private widget.ScrollPane Scroll;
    private widget.ComboBox Tahun;
    private widget.TextBox Tcari;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.Label jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private widget.Label label11;
    private widget.panelisi panelGlass6;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    public void tampildata(String tahun, String bulan, String cari) {
        try {
            headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
	    headers.add("X-Cons-ID",koneksiDB.CONSIDAPIBPJS());
	    utc=String.valueOf(api.GetUTCdatetimeAsString());
	    headers.add("X-Timestamp",utc);
	    headers.add("X-Signature",api.getHmac(utc));
            headers.add("user_key",koneksiDB.USERKEYAPIBPJS());
	    requestEntity = new HttpEntity(headers);
            URL = link+"/Rujukan/Khusus/List/Bulan/"+bulan+"/Tahun/"+tahun;
            root = mapper.readTree(api.getRest().exchange(URL, HttpMethod.GET, requestEntity, String.class).getBody());
            nameNode = root.path("metaData");
            if(nameNode.path("code").asText().equals("200")){
                Valid.tabelKosong(tabMode);
                response = mapper.readTree(api.Decrypt(root.path("response").asText(),utc));
                //response = root.path("response");
                if(response.path("rujukan").isArray()){
                    for(JsonNode list:response.path("rujukan")){                     
                            if(list.path("nokapst").asText().toLowerCase().contains(cari.toLowerCase())||
                                    list.path("norujukan").asText().toLowerCase().contains(cari.toLowerCase())||
                                    list.path("nmpst").asText().toLowerCase().contains(cari.toLowerCase())){
                            tabMode.addRow(new Object[]{
                                list.path("idrujukan").asText(),
                                list.path("norujukan").asText(),
                                list.path("nokapst").asText(),
                                list.path("nmpst").asText(),
                                list.path("diagppk").asText(),
                                list.path("tglrujukan_awal").asText(),
                                list.path("tglrujukan_berakhir").asText() 
                            });
                          }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, nameNode.path("message").asText());
            }
        } catch (Exception ex) {
            System.out.println("Notifikasi : " + ex);
            if (ex.toString().contains("UnknownHostException")) {
                JOptionPane.showMessageDialog(rootPane, "Koneksi ke server BPJS terputus...!");
            }
        }
          LCount.setText(""+tabMode.getRowCount());
    }  
    
    private void tampildataYangBelumAda(String tahun, String bulan, String cari) {
            try {
                headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.add("X-Cons-ID", koneksiDB.CONSIDAPIBPJS());
                utc = String.valueOf(api.GetUTCdatetimeAsString());
                headers.add("X-Timestamp", utc);
                headers.add("X-Signature", api.getHmac(utc));
                headers.add("user_key", koneksiDB.USERKEYAPIBPJS());
                requestEntity = new HttpEntity(headers);

                URL = link + "/Rujukan/Khusus/List/Bulan/" + bulan + "/Tahun/" + tahun;
                root = mapper.readTree(api.getRest().exchange(URL, HttpMethod.GET, requestEntity, String.class).getBody());
                nameNode = root.path("metaData");

                if (nameNode.path("code").asText().equals("200")) {
                    Valid.tabelKosong(tabMode);
                    response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));

                    if (response.path("rujukan").isArray()) {
                        for (JsonNode list : response.path("rujukan")) {
                            String noRujukan = list.path("norujukan").asText();

                            // 🔍 Cek apakah data sudah tersimpan di database lokal
                            boolean sudahAda = Sequel.cariInteger(
                                "SELECT COUNT(*) FROM bridging_rujukan_bpjs_khusus WHERE no_rujukan = ?",
                                noRujukan
                            ) > 0;

                            if (sudahAda) {
                                // System.out.println("Lewati: " + noRujukan);
                                continue; // lewati data yang sudah ada
                            }

                            // 🔎 Filter pencarian
                            if (list.path("nokapst").asText().toLowerCase().contains(cari.toLowerCase()) ||
                                list.path("norujukan").asText().toLowerCase().contains(cari.toLowerCase()) ||
                                list.path("nmpst").asText().toLowerCase().contains(cari.toLowerCase())) {

                                // ✅ Tambahkan hanya data baru ke tabel GUI
                                tabMode.addRow(new Object[]{
                                    list.path("idrujukan").asText(),
                                    list.path("norujukan").asText(),
                                    list.path("nokapst").asText(),
                                    list.path("nmpst").asText(),
                                    list.path("diagppk").asText(),
                                    list.path("tglrujukan_awal").asText(),
                                    list.path("tglrujukan_berakhir").asText()
                                });
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, nameNode.path("message").asText());
                }

            } catch (Exception ex) {
                System.out.println("Notifikasi : " + ex);
                if (ex.toString().contains("UnknownHostException")) {
                    JOptionPane.showMessageDialog(rootPane, "Koneksi ke server BPJS terputus...!");
                }
            }

            LCount.setText("" + tabMode.getRowCount());
        }


    public JTable getTable(){
        return tbKamar;
    }
       
    
     private void getData() {
        if(tbKamar.getSelectedRow()!= -1){
              try {
//                    tampilobat(tbKamar.getValueAt(tbKamar.getSelectedRow(),3).toString(),Valid.SetTgl(TanggalAwal.getSelectedItem().toString()), Valid.SetTgl(TanggalAkhir.getSelectedItem().toString()));
            } catch (Exception e) {
                 System.out.println("Notif : "+e);
            }
        }
     
     }
    
}
