/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */

package modifikasi;


import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kepegawaian.DlgCariPetugas;

/**
 *
 * @author dosen
 */
public final class DlgCetakSHK extends javax.swing.JDialog {

    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private DlgCariPetugas dlgpetugas= new DlgCariPetugas(null,false);
    private DlgCariPetugas dlgkordinator= new DlgCariPetugas(null,false);
    /** Creates new form DlgPenyakit
     *@param parent
     *@param modal */
    public DlgCetakSHK(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(628,674);
        
         dlgpetugas.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(dlgpetugas.getTable().getSelectedRow()!= -1){                   
                    Tnmptg.setText(dlgpetugas.getTable().getValueAt(dlgpetugas.getTable().getSelectedRow(),1).toString());
                }            
                BtnPetugas.requestFocus();
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
         
         dlgkordinator.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(dlgkordinator.getTable().getSelectedRow()!= -1){                   
                    Tnmkordinator.setText(dlgkordinator.getTable().getValueAt(dlgkordinator.getTable().getSelectedRow(),1).toString());
                }            
                Btnkordinator.requestFocus();
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoMr = new widget.TextBox();
        internalFrame5 = new widget.InternalFrame();
        panelBiasa4 = new widget.PanelBiasa();
        jLabel37 = new widget.Label();
        BtnPrint5 = new widget.Button();
        BtnKeluar4 = new widget.Button();
        BtnPetugas = new widget.Button();
        jLabel24 = new widget.Label();
        Tnmptg = new widget.TextBox();
        Tnmkordinator = new widget.TextBox();
        Btnkordinator = new widget.Button();

        NoMr.setEditable(false);
        NoMr.setHighlighter(null);
        NoMr.setName("NoMr"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 235, 225)), "::[ Cetak Surat Keterangan Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 70, 50))); // NOI18N
        internalFrame5.setName("internalFrame5"); // NOI18N
        internalFrame5.setLayout(new java.awt.BorderLayout(1, 1));

        panelBiasa4.setName("panelBiasa4"); // NOI18N
        panelBiasa4.setLayout(null);

        jLabel37.setText("Nama Petugas :");
        jLabel37.setName("jLabel37"); // NOI18N
        panelBiasa4.add(jLabel37);
        jLabel37.setBounds(7, 10, 140, 23);

        BtnPrint5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint5.setMnemonic('T');
        BtnPrint5.setText("Cetak");
        BtnPrint5.setToolTipText("Alt+T");
        BtnPrint5.setName("BtnPrint5"); // NOI18N
        BtnPrint5.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrint5ActionPerformed(evt);
            }
        });
        panelBiasa4.add(BtnPrint5);
        BtnPrint5.setBounds(10, 80, 100, 30);

        BtnKeluar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar4.setMnemonic('U');
        BtnKeluar4.setText("Tutup");
        BtnKeluar4.setToolTipText("Alt+U");
        BtnKeluar4.setName("BtnKeluar4"); // NOI18N
        BtnKeluar4.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar4ActionPerformed(evt);
            }
        });
        panelBiasa4.add(BtnKeluar4);
        BtnKeluar4.setBounds(430, 80, 100, 30);

        BtnPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPetugas.setMnemonic('6');
        BtnPetugas.setToolTipText("ALt+6");
        BtnPetugas.setName("BtnPetugas"); // NOI18N
        BtnPetugas.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPetugasActionPerformed(evt);
            }
        });
        panelBiasa4.add(BtnPetugas);
        BtnPetugas.setBounds(470, 10, 28, 23);

        jLabel24.setText("Kordinator / Karu :");
        jLabel24.setName("jLabel24"); // NOI18N
        jLabel24.setPreferredSize(new java.awt.Dimension(60, 23));
        panelBiasa4.add(jLabel24);
        jLabel24.setBounds(7, 40, 140, 23);

        Tnmptg.setEditable(false);
        Tnmptg.setHighlighter(null);
        Tnmptg.setName("Tnmptg"); // NOI18N
        panelBiasa4.add(Tnmptg);
        Tnmptg.setBounds(160, 10, 310, 23);

        Tnmkordinator.setEditable(false);
        Tnmkordinator.setName("Tnmkordinator"); // NOI18N
        Tnmkordinator.setPreferredSize(new java.awt.Dimension(300, 23));
        panelBiasa4.add(Tnmkordinator);
        Tnmkordinator.setBounds(160, 40, 310, 23);

        Btnkordinator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        Btnkordinator.setMnemonic('6');
        Btnkordinator.setToolTipText("ALt+6");
        Btnkordinator.setName("Btnkordinator"); // NOI18N
        Btnkordinator.setPreferredSize(new java.awt.Dimension(28, 23));
        Btnkordinator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkordinatorActionPerformed(evt);
            }
        });
        panelBiasa4.add(Btnkordinator);
        Btnkordinator.setBounds(470, 40, 28, 23);

        internalFrame5.add(panelBiasa4, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        emptTeks();
    }//GEN-LAST:event_formWindowOpened

    private void BtnPrint5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrint5ActionPerformed
        if(Tnmptg.getText().trim().equals("")||Tnmkordinator.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Silahkan anda pilih dulu petugas dan kordinator...!!!");
        }else{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Map<String, Object> param = new HashMap<>();
            param.put("kotars",akses.getkabupatenrs());
            param.put("norm",NoMr.getText());
            param.put("petugas",Tnmptg.getText());
            param.put("kordinator",Tnmkordinator.getText());
            Valid.MyReport("rptBuktiPelayananSHK.jasper","report","::[ Surat Pelayanan SHK ]::",param);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPrint5ActionPerformed

    private void BtnKeluar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar4ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluar4ActionPerformed

    private void BtnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPetugasActionPerformed
        dlgpetugas.emptTeks();
        dlgpetugas.isCek();
        //petugas.setModal(true);
        dlgpetugas.setSize(900,900);
        dlgpetugas.setLocationRelativeTo(internalFrame5);
        dlgpetugas.setVisible(true);
    }//GEN-LAST:event_BtnPetugasActionPerformed

    private void BtnkordinatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkordinatorActionPerformed
        dlgkordinator.emptTeks();
        dlgkordinator.isCek();
        //petugas.setModal(true);
        dlgkordinator.setSize(900,900);
        dlgkordinator.setLocationRelativeTo(internalFrame5);
        dlgkordinator.setVisible(true);
    }//GEN-LAST:event_BtnkordinatorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCetakSHK dialog = new DlgCetakSHK(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar4;
    private widget.Button BtnPetugas;
    private widget.Button BtnPrint5;
    private widget.Button Btnkordinator;
    private widget.TextBox NoMr;
    private widget.TextBox Tnmkordinator;
    private widget.TextBox Tnmptg;
    private widget.InternalFrame internalFrame5;
    private widget.Label jLabel24;
    private widget.Label jLabel37;
    private widget.PanelBiasa panelBiasa4;
    // End of variables declaration//GEN-END:variables

    public void emptTeks() {
        Tnmptg.setText("");        
        Tnmkordinator.setText("");
    }    
    
    public void SetNoRM(String norm) {
        NoMr.setText(norm);   
    }
}
