/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modifikasi;

import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author windiartonugroho
 */
public class forminformasiuser extends javax.swing.JFrame {
    private  Connection koneksi=koneksiDB.condb();
    private  sekuel Sequel=new sekuel();
    private  String requestJson,URL="",utc="",link="",datajam="",nol_jam = "",nol_menit = "",nol_detik = "",jam="",menit="",
                detik="",hari="",noresep="",kodepoli="",kodedokter="",kodebpjs=Sequel.cariIsi("select password_asuransi.kd_pj from password_asuransi");
    private  PreparedStatement ps,ps2;
    private  ResultSet rs,rs2;
    private static forminformasiuser myInstance;

    /**
     * Creates new form frmUtama
     */
    public forminformasiuser() {
        initComponents();
        this.setSize(490,340);
        tampil();
    }

     public static forminformasiuser getInstance() {
        if (myInstance == null)
            myInstance = new forminformasiuser();

        return myInstance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TeksArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        BtnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TeksArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informasi");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(274, 60));

        TeksArea.setBackground(new java.awt.Color(255, 51, 51));
        TeksArea.setColumns(20);
        TeksArea.setRows(5);
        jScrollPane1.setViewportView(TeksArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        BtnUpdate.setText("Update Informasi");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUpdate);

        jLabel2.setPreferredSize(new java.awt.Dimension(30, 23));
        jPanel1.add(jLabel2);

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKeluar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        TeksArea1.setEditable(false);
        TeksArea1.setBackground(new java.awt.Color(204, 204, 204));
        TeksArea1.setColumns(20);
        TeksArea1.setRows(5);
        TeksArea1.setPreferredSize(new java.awt.Dimension(272, 60));
        jScrollPane2.setViewportView(TeksArea1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        if(TeksArea.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf Informasi / Pembertahuan tidak boleh Kosong");
        }else{
            Sequel.queryu("delete from catatan_informasi_user");
            Sequel.menyimpan("catatan_informasi_user","'1','V.03032025(Vedika,Bank-Mandiri,ERM)','"+TeksArea.getText()+"' ");
            tampil();
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forminformasiuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forminformasiuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forminformasiuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forminformasiuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forminformasiuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextArea TeksArea;
    private javax.swing.JTextArea TeksArea1;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private void tampil(){                                         
           
           try {
               ps=koneksi.prepareStatement(
                 "SELECT catatan FROM catatan_informasi_user ciu order by ciu.no DESC limit 1 ");
            try {
                rs=ps.executeQuery();
                while(rs.next()){
                            TeksArea.append(rs.getString("catatan"));
                        }  
   
                    }catch (Exception ex) {
                        System.out.println("Notifikasi : "+ex);
                    }
                   
                    } catch (Exception e) {
                    }
               

                }

                public void iscek(){          
                    if(akses.getkode().equals("Admin Utama")){
                            BtnUpdate.setVisible(true);
                            TeksArea1.append("Informasi dan Pemberitahuan Untuk Pengguna Simrs..\n");
                    }else{
                            BtnUpdate.setVisible(false);
                            TeksArea1.append("Informasi dan Pemberitahuan Untuk Pengguna Simrs..\n");
                        }
                }
            };