package modifikasi;
import simrskhanza.*;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class DlgSuratKUNH extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,psresep;
    private ResultSet rs,rsobat;
    private int i;
    private String kddokter="",RESEPRAJALKEPLAN="",resep="";

    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgSuratKUNH(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

       tabMode=new DefaultTableModel(null,new Object[]{
            "No.Surat","No.Rawat","No.R.M.","Nama Pasien","Dari Tanggal","Sampai Tanggal/ Tgl.Perkiraan Lahir","Lama Sakit","Asesmen","Keterangan","Jenis"
        }){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbDokter.setModel(tabMode);

        //tbObat.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbObat.getBackground()));
        tbDokter.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbDokter.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 10; i++) {
            TableColumn column = tbDokter.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(105);
            }else if(i==1){
                column.setPreferredWidth(105);
            }else if(i==2){
                column.setPreferredWidth(70);
            }else if(i==3){
                column.setPreferredWidth(170);
            }else if(i==4){
                column.setPreferredWidth(90);
            }else if(i==5){
                column.setPreferredWidth(170);
            }else if(i==6){
                column.setPreferredWidth(100);
            }else if(i==7){
                column.setPreferredWidth(170);
            }else if(i==8){
                column.setPreferredWidth(170);
            }else if(i==9){
                column.setPreferredWidth(170);
            }
        }
        tbDokter.setDefaultRenderer(Object.class, new WarnaTable());
        
        
        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
        KetCutiMelahirkan.setDocument(new batasInput((int)200).getKata(KetCutiMelahirkan));
        if(koneksiDB.CARICEPAT().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
            });
        }   
        ChkInput.setSelected(true);
        isForm();
        autoNomorSurat();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TNoRm = new widget.TextBox();
        label42 = new widget.Label();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnCetakSurat = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        jPanel2 = new javax.swing.JPanel();
        panelisi2 = new widget.panelisi();
        jLabel19 = new widget.Label();
        DTPCari1 = new widget.Tanggal();
        jLabel21 = new widget.Label();
        DTPCari2 = new widget.Tanggal();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        panelisi1 = new widget.panelisi();
        BtnSimpanSuratSakit = new widget.Button();
        BtnSimpanSuratCuti = new widget.Button();
        BtnSimpanSuratTerbang = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnKeluar = new widget.Button();
        scrollPane1 = new widget.ScrollPane();
        tbDokter = new widget.Table();
        PanelInput = new javax.swing.JPanel();
        FormInput = new widget.PanelBiasa();
        label40 = new widget.Label();
        label41 = new widget.Label();
        TanggalPerkiraan = new widget.Tanggal();
        scrollPane17 = new widget.ScrollPane();
        KetCutiMelahirkan = new widget.TextArea();
        jLabel4 = new widget.Label();
        TNoRw = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TPasien = new widget.TextBox();
        jLabel3 = new widget.Label();
        NoSurat = new widget.TextBox();
        jLabel13 = new widget.Label();
        TanggalAwal = new widget.Tanggal();
        TanggalAkhir = new widget.Tanggal();
        jLabel18 = new widget.Label();
        LamaSakit = new widget.TextBox();
        jLabel14 = new widget.Label();
        jLabel15 = new widget.Label();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0));
        jLabel16 = new widget.Label();
        label43 = new widget.Label();
        scrollPane18 = new widget.ScrollPane();
        KetSuratTerbang = new widget.TextArea();
        label44 = new widget.Label();
        scrollPane19 = new widget.ScrollPane();
        Assement = new widget.TextArea();
        label45 = new widget.Label();
        scrollPane20 = new widget.ScrollPane();
        AssementCuti = new widget.TextArea();
        ChkInput = new widget.CekBox();

        TNoRm.setEditable(false);
        TNoRm.setHighlighter(null);
        TNoRm.setName("TNoRm"); // NOI18N
        TNoRm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNoRmKeyPressed(evt);
            }
        });

        label42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label42.setText("Minggu");
        label42.setName("label42"); // NOI18N
        label42.setPreferredSize(new java.awt.Dimension(65, 23));

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        MnCetakSurat.setBackground(new java.awt.Color(250, 250, 250));
        MnCetakSurat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnCetakSurat.setForeground(new java.awt.Color(50, 50, 50));
        MnCetakSurat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnCetakSurat.setText("Cetak Surat");
        MnCetakSurat.setName("MnCetakSurat"); // NOI18N
        MnCetakSurat.setPreferredSize(new java.awt.Dimension(200, 26));
        MnCetakSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCetakSuratActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnCetakSurat);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Surat Sakit, Cuti, dan Terbang ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(816, 100));
        jPanel2.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi2.setBackground(new java.awt.Color(255, 150, 255));
        panelisi2.setName("panelisi2"); // NOI18N
        panelisi2.setPreferredSize(new java.awt.Dimension(100, 44));
        panelisi2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        jLabel19.setText("Tgl. Surat :");
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(67, 23));
        panelisi2.add(jLabel19);

        DTPCari1.setForeground(new java.awt.Color(50, 70, 50));
        DTPCari1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22-01-2025" }));
        DTPCari1.setDisplayFormat("dd-MM-yyyy");
        DTPCari1.setName("DTPCari1"); // NOI18N
        DTPCari1.setOpaque(false);
        DTPCari1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelisi2.add(DTPCari1);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("s.d.");
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(23, 23));
        panelisi2.add(jLabel21);

        DTPCari2.setForeground(new java.awt.Color(50, 70, 50));
        DTPCari2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22-01-2025" }));
        DTPCari2.setDisplayFormat("dd-MM-yyyy");
        DTPCari2.setName("DTPCari2"); // NOI18N
        DTPCari2.setOpaque(false);
        DTPCari2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelisi2.add(DTPCari2);

        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi2.add(label9);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(200, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi2.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelisi2.add(BtnCari);

        label10.setText("Record :");
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(70, 23));
        panelisi2.add(label10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi2.add(LCount);

        jPanel2.add(panelisi2, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 44));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpanSuratSakit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        BtnSimpanSuratSakit.setMnemonic('S');
        BtnSimpanSuratSakit.setText("Simpan S.Sakit");
        BtnSimpanSuratSakit.setToolTipText("Alt+S");
        BtnSimpanSuratSakit.setName("BtnSimpanSuratSakit"); // NOI18N
        BtnSimpanSuratSakit.setPreferredSize(new java.awt.Dimension(150, 30));
        BtnSimpanSuratSakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanSuratSakitActionPerformed(evt);
            }
        });
        BtnSimpanSuratSakit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanSuratSakitKeyPressed(evt);
            }
        });
        panelisi1.add(BtnSimpanSuratSakit);

        BtnSimpanSuratCuti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        BtnSimpanSuratCuti.setMnemonic('S');
        BtnSimpanSuratCuti.setText("Simpan S.Cuti");
        BtnSimpanSuratCuti.setToolTipText("Alt+S");
        BtnSimpanSuratCuti.setName("BtnSimpanSuratCuti"); // NOI18N
        BtnSimpanSuratCuti.setPreferredSize(new java.awt.Dimension(150, 30));
        BtnSimpanSuratCuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanSuratCutiActionPerformed(evt);
            }
        });
        BtnSimpanSuratCuti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanSuratCutiKeyPressed(evt);
            }
        });
        panelisi1.add(BtnSimpanSuratCuti);

        BtnSimpanSuratTerbang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        BtnSimpanSuratTerbang.setMnemonic('S');
        BtnSimpanSuratTerbang.setText("Simpan S.Terbang");
        BtnSimpanSuratTerbang.setToolTipText("Alt+S");
        BtnSimpanSuratTerbang.setName("BtnSimpanSuratTerbang"); // NOI18N
        BtnSimpanSuratTerbang.setPreferredSize(new java.awt.Dimension(150, 30));
        BtnSimpanSuratTerbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanSuratTerbangActionPerformed(evt);
            }
        });
        BtnSimpanSuratTerbang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanSuratTerbangKeyPressed(evt);
            }
        });
        panelisi1.add(BtnSimpanSuratTerbang);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Reset");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        panelisi1.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelisi1.add(BtnHapus);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        jPanel2.add(panelisi1, java.awt.BorderLayout.CENTER);

        internalFrame1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tbDokter.setAutoCreateRowSorter(true);
        tbDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDokter.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbDokter.setComponentPopupMenu(jPopupMenu1);
        tbDokter.setName("tbDokter"); // NOI18N
        tbDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDokterMouseClicked(evt);
            }
        });
        tbDokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbDokterKeyPressed(evt);
            }
        });
        scrollPane1.setViewportView(tbDokter);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setOpaque(false);
        PanelInput.setPreferredSize(new java.awt.Dimension(660, 220));
        PanelInput.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(660, 107));
        FormInput.setLayout(null);

        label40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label40.setText("Keterangan :");
        label40.setName("label40"); // NOI18N
        label40.setPreferredSize(new java.awt.Dimension(65, 23));
        FormInput.add(label40);
        label40.setBounds(370, 100, 70, 23);

        label41.setText("Perkiraan Kelahiran :");
        label41.setName("label41"); // NOI18N
        label41.setPreferredSize(new java.awt.Dimension(65, 23));
        FormInput.add(label41);
        label41.setBounds(370, 169, 100, 23);

        TanggalPerkiraan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22-01-2025" }));
        TanggalPerkiraan.setDisplayFormat("dd-MM-yyyy");
        TanggalPerkiraan.setName("TanggalPerkiraan"); // NOI18N
        TanggalPerkiraan.setOpaque(false);
        TanggalPerkiraan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TanggalPerkiraanItemStateChanged(evt);
            }
        });
        TanggalPerkiraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TanggalPerkiraanKeyPressed(evt);
            }
        });
        FormInput.add(TanggalPerkiraan);
        TanggalPerkiraan.setBounds(470, 169, 120, 23);

        scrollPane17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane17.setName("scrollPane17"); // NOI18N

        KetCutiMelahirkan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KetCutiMelahirkan.setColumns(20);
        KetCutiMelahirkan.setRows(5);
        KetCutiMelahirkan.setName("KetCutiMelahirkan"); // NOI18N
        KetCutiMelahirkan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KetCutiMelahirkanKeyPressed(evt);
            }
        });
        scrollPane17.setViewportView(KetCutiMelahirkan);

        FormInput.add(scrollPane17);
        scrollPane17.setBounds(440, 100, 170, 30);

        jLabel4.setText("No.Rawat :");
        jLabel4.setName("jLabel4"); // NOI18N
        FormInput.add(jLabel4);
        jLabel4.setBounds(0, 10, 95, 23);

        TNoRw.setHighlighter(null);
        TNoRw.setName("TNoRw"); // NOI18N
        TNoRw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNoRwKeyPressed(evt);
            }
        });
        FormInput.add(TNoRw);
        TNoRw.setBounds(99, 10, 141, 23);

        TNoRM.setEditable(false);
        TNoRM.setHighlighter(null);
        TNoRM.setName("TNoRM"); // NOI18N
        TNoRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNoRMKeyPressed(evt);
            }
        });
        FormInput.add(TNoRM);
        TNoRM.setBounds(242, 10, 111, 23);

        TPasien.setEditable(false);
        TPasien.setHighlighter(null);
        TPasien.setName("TPasien"); // NOI18N
        TPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TPasienKeyPressed(evt);
            }
        });
        FormInput.add(TPasien);
        TPasien.setBounds(355, 10, 365, 23);

        jLabel3.setText("No. Surat :");
        jLabel3.setName("jLabel3"); // NOI18N
        FormInput.add(jLabel3);
        jLabel3.setBounds(0, 40, 95, 23);

        NoSurat.setHighlighter(null);
        NoSurat.setName("NoSurat"); // NOI18N
        NoSurat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoSuratKeyPressed(evt);
            }
        });
        FormInput.add(NoSurat);
        NoSurat.setBounds(99, 40, 410, 23);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Surat Cuti Melahirkan");
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        FormInput.add(jLabel13);
        jLabel13.setBounds(420, 70, 140, 23);

        TanggalAwal.setForeground(new java.awt.Color(50, 70, 50));
        TanggalAwal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22-01-2025" }));
        TanggalAwal.setDisplayFormat("dd-MM-yyyy");
        TanggalAwal.setName("TanggalAwal"); // NOI18N
        TanggalAwal.setOpaque(false);
        TanggalAwal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TanggalAwalItemStateChanged(evt);
            }
        });
        TanggalAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalAwalActionPerformed(evt);
            }
        });
        TanggalAwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TanggalAwalKeyPressed(evt);
            }
        });
        FormInput.add(TanggalAwal);
        TanggalAwal.setBounds(120, 100, 90, 23);

        TanggalAkhir.setForeground(new java.awt.Color(50, 70, 50));
        TanggalAkhir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22-01-2025" }));
        TanggalAkhir.setDisplayFormat("dd-MM-yyyy");
        TanggalAkhir.setName("TanggalAkhir"); // NOI18N
        TanggalAkhir.setOpaque(false);
        TanggalAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalAkhirActionPerformed(evt);
            }
        });
        TanggalAkhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TanggalAkhirKeyPressed(evt);
            }
        });
        FormInput.add(TanggalAkhir);
        TanggalAkhir.setBounds(230, 100, 90, 23);

        jLabel18.setText("Lama Sakit :");
        jLabel18.setName("jLabel18"); // NOI18N
        FormInput.add(jLabel18);
        jLabel18.setBounds(50, 130, 70, 23);

        LamaSakit.setHighlighter(null);
        LamaSakit.setName("LamaSakit"); // NOI18N
        LamaSakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamaSakitActionPerformed(evt);
            }
        });
        LamaSakit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LamaSakitKeyPressed(evt);
            }
        });
        FormInput.add(LamaSakit);
        LamaSakit.setBounds(120, 130, 106, 23);

        jLabel14.setText("Dari Tanggal :");
        jLabel14.setName("jLabel14"); // NOI18N
        FormInput.add(jLabel14);
        jLabel14.setBounds(40, 100, 80, 23);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Surat Sakit");
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        FormInput.add(jLabel15);
        jLabel15.setBounds(160, 70, 80, 23);

        filler1.setBackground(new java.awt.Color(51, 51, 51));
        filler1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        filler1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        filler1.setForeground(new java.awt.Color(51, 51, 51));
        filler1.setName("filler1"); // NOI18N
        FormInput.add(filler1);
        filler1.setBounds(640, 70, 10, 120);

        filler2.setBackground(new java.awt.Color(51, 51, 51));
        filler2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        filler2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        filler2.setForeground(new java.awt.Color(51, 51, 51));
        filler2.setName("filler2"); // NOI18N
        FormInput.add(filler2);
        filler2.setBounds(340, 70, 10, 120);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Surat Terbang");
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        FormInput.add(jLabel16);
        jLabel16.setBounds(730, 70, 140, 23);

        label43.setText("Keterangan :");
        label43.setName("label43"); // NOI18N
        label43.setPreferredSize(new java.awt.Dimension(65, 23));
        FormInput.add(label43);
        label43.setBounds(680, 100, 65, 23);

        scrollPane18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane18.setName("scrollPane18"); // NOI18N

        KetSuratTerbang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        KetSuratTerbang.setColumns(20);
        KetSuratTerbang.setRows(5);
        KetSuratTerbang.setName("KetSuratTerbang"); // NOI18N
        KetSuratTerbang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KetSuratTerbangKeyPressed(evt);
            }
        });
        scrollPane18.setViewportView(KetSuratTerbang);

        FormInput.add(scrollPane18);
        scrollPane18.setBounds(750, 100, 170, 30);

        label44.setText("Assement :");
        label44.setName("label44"); // NOI18N
        label44.setPreferredSize(new java.awt.Dimension(65, 23));
        FormInput.add(label44);
        label44.setBounds(680, 140, 65, 23);

        scrollPane19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane19.setName("scrollPane19"); // NOI18N

        Assement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Assement.setColumns(20);
        Assement.setRows(5);
        Assement.setName("Assement"); // NOI18N
        Assement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AssementKeyPressed(evt);
            }
        });
        scrollPane19.setViewportView(Assement);

        FormInput.add(scrollPane19);
        scrollPane19.setBounds(750, 140, 170, 30);

        label45.setText("Assement :");
        label45.setName("label45"); // NOI18N
        label45.setPreferredSize(new java.awt.Dimension(65, 23));
        FormInput.add(label45);
        label45.setBounds(370, 138, 65, 23);

        scrollPane20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane20.setName("scrollPane20"); // NOI18N

        AssementCuti.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AssementCuti.setColumns(20);
        AssementCuti.setRows(5);
        AssementCuti.setName("AssementCuti"); // NOI18N
        AssementCuti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AssementCutiKeyPressed(evt);
            }
        });
        scrollPane20.setViewportView(AssementCuti);

        FormInput.add(scrollPane20);
        scrollPane20.setBounds(440, 138, 170, 30);

        PanelInput.add(FormInput, java.awt.BorderLayout.CENTER);

        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setMnemonic('I');
        ChkInput.setText(".: Input Data");
        ChkInput.setToolTipText("Alt+I");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setPreferredSize(new java.awt.Dimension(192, 20));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        PanelInput.add(ChkInput, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            tbDokter.requestFocus();
        }
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnKeluar);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void tbDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDokterMouseClicked
        if(tabMode.getRowCount()!=0){
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
}//GEN-LAST:event_tbDokterMouseClicked

    private void tbDokterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDokterKeyPressed
        if(tabMode.getRowCount()!=0){
            if((evt.getKeyCode()==KeyEvent.VK_ENTER)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
}//GEN-LAST:event_tbDokterKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if(TNoRw.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Pilih dulu data yang akan Anda hapus dengan menklik data pada tabel...!!!");
            tbDokter.requestFocus();
        }else{
            Valid.hapusTable(tabMode,NoSurat,"m_surat_kunh","no_surat");
            tampil();
        }
}//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnHapusActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnBatal, BtnKeluar);
        }
}//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
            dispose();  
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){            
            dispose();              
        }else{Valid.pindah(evt,BtnHapus,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnSimpanSuratSakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanSuratSakitActionPerformed
        if(TNoRw.getText().trim().equals("")){
            Valid.textKosong(TNoRw,"No. Rawat");
        }else{
                   // autoNomorSurat();
                    Sequel.menyimpan("m_surat_kunh","?,?,?,?,?,?,?,?","Surat",8,new String[]{
                        NoSurat.getText(),TNoRw.getText(),Valid.SetTgl(TanggalAwal.getSelectedItem()+""),Valid.SetTgl(TanggalAkhir.getSelectedItem()+""),
                        LamaSakit.getText(),"-","-",jLabel15.getText()
                    });                    
                    tampil();
                    emptTeks();

        }
}//GEN-LAST:event_BtnSimpanSuratSakitActionPerformed

    private void BtnSimpanSuratSakitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanSuratSakitKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanSuratSakitActionPerformed(null);
        }else{
            Valid.pindah(evt,BtnKeluar,BtnSimpanSuratCuti);
        }
}//GEN-LAST:event_BtnSimpanSuratSakitKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        ChkInput.setSelected(true);
        isForm(); 
        emptTeks();
}//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            emptTeks();
        }else{Valid.pindah(evt, BtnSimpanSuratSakit, BtnHapus);}
}//GEN-LAST:event_BtnBatalKeyPressed
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        isForm();
    }//GEN-LAST:event_ChkInputActionPerformed

    private void TanggalPerkiraanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TanggalPerkiraanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPerkiraanItemStateChanged

    private void TanggalPerkiraanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TanggalPerkiraanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPerkiraanKeyPressed

    private void TNoRmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNoRmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoRmKeyPressed

    private void KetCutiMelahirkanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KetCutiMelahirkanKeyPressed
        Valid.pindah2(evt,TNoRw,BtnSimpanSuratSakit);
    }//GEN-LAST:event_KetCutiMelahirkanKeyPressed

    private void TNoRwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNoRwKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
        }else{
            Valid.pindah(evt,TCari,LamaSakit);
        }
    }//GEN-LAST:event_TNoRwKeyPressed

    private void TNoRMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNoRMKeyPressed

    }//GEN-LAST:event_TNoRMKeyPressed

    private void TPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPasienKeyPressed
        Valid.pindah(evt,TCari,BtnSimpanSuratSakit);
    }//GEN-LAST:event_TPasienKeyPressed

    private void NoSuratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoSuratKeyPressed
        Valid.pindah(evt,TCari,TanggalAwal);
    }//GEN-LAST:event_NoSuratKeyPressed

    private void TanggalAwalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TanggalAwalItemStateChanged

    }//GEN-LAST:event_TanggalAwalItemStateChanged

    private void TanggalAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalAwalActionPerformed

    private void TanggalAwalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TanggalAwalKeyPressed
        Valid.pindah(evt,NoSurat,TanggalAkhir);
    }//GEN-LAST:event_TanggalAwalKeyPressed

    private void TanggalAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalAkhirActionPerformed

    private void TanggalAkhirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TanggalAkhirKeyPressed
        Valid.pindah(evt,TanggalAwal,LamaSakit);
    }//GEN-LAST:event_TanggalAkhirKeyPressed

    private void LamaSakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamaSakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LamaSakitActionPerformed

    private void LamaSakitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LamaSakitKeyPressed
        Valid.pindah(evt,TanggalAkhir,BtnSimpanSuratSakit);
    }//GEN-LAST:event_LamaSakitKeyPressed

    private void KetSuratTerbangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KetSuratTerbangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KetSuratTerbangKeyPressed

    private void AssementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AssementKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssementKeyPressed

    private void BtnSimpanSuratCutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanSuratCutiActionPerformed
    if(TNoRw.getText().trim().equals("")){
               Valid.textKosong(TNoRw,"No. Rawat");
           }else{
                    //    autoNomorSurat();
                       Sequel.menyimpan("m_surat_kunh","?,?,?,?,?,?,?,?","Surat",8,new String[]{
                           NoSurat.getText(),TNoRw.getText(),Valid.SetTgl(TanggalAwal.getSelectedItem()+""),Valid.SetTgl(TanggalPerkiraan.getSelectedItem()+""),
                           "-",AssementCuti.getText(),KetCutiMelahirkan.getText(),jLabel13.getText()
                       });                    
                       tampil();
                       emptTeks();

           }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSimpanSuratCutiActionPerformed

    private void BtnSimpanSuratCutiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanSuratCutiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSimpanSuratCutiKeyPressed

    private void BtnSimpanSuratTerbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanSuratTerbangActionPerformed
        if(TNoRw.getText().trim().equals("")){
               Valid.textKosong(TNoRw,"No. Rawat");
           }else{
            
                  //      autoNomorSurat();
                       Sequel.menyimpan("m_surat_kunh","?,?,?,?,?,?,?,?","Surat",8,new String[]{
                           NoSurat.getText(),TNoRw.getText(),Valid.SetTgl(TanggalAwal.getSelectedItem()+""),Valid.SetTgl(TanggalAkhir.getSelectedItem()+""),
                           "-",Assement.getText(),KetSuratTerbang.getText(),jLabel16.getText()
                       });                    
                       tampil();
                       emptTeks();

           } 
    }//GEN-LAST:event_BtnSimpanSuratTerbangActionPerformed

    private void BtnSimpanSuratTerbangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanSuratTerbangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSimpanSuratTerbangKeyPressed

    private void MnCetakSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCetakSuratActionPerformed
        if(NoSurat.getText().trim().equals("")||TNoRw.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Silahkan anda pilih dulu pasien...!!!");
        }else{
                if(tbDokter.getValueAt(tbDokter.getSelectedRow(),9).toString().equals("Surat Sakit")){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                    param.put("hari",LamaSakit.getText());
                    param.put("TanggalAwal",TanggalAwal.getSelectedItem().toString());
                    param.put("TanggalAkhir",TanggalAkhir.getSelectedItem().toString());
                    param.put("nosakit",NoSurat.getText());
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    param.put("dpjp",Sequel.cariIsi("select d.nm_dokter from reg_periksa  rp inner join dokter d on d.kd_dokter=rp.kd_dokter where rp.no_rawat='"+TNoRw.getText()+"' "));
                    param.put("logo",Sequel.cariGambar("select setting.logo from setting"));
                Valid.MyReportqry("rptSuratSakit5.jasper","report","::[ Surat Sakit ]::",
                    "select DATE_FORMAT(reg_periksa.tgl_registrasi,'%dd-%mm-%YYYY')as tgl_registrasi,perusahaan_pasien.nama_perusahaan,reg_periksa.no_rawat,dokter.nm_dokter,pasien.keluarga,pasien.namakeluarga,pasien.tgl_lahir,pasien.jk," +
                    " pasien.nm_pasien,concat(reg_periksa.umurdaftar,' ',reg_periksa.sttsumur)as umur,pasien.pekerjaan,concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) as alamat, dokter.no_ijn_praktek" +
                    " from reg_periksa inner join pasien inner join dokter inner join kelurahan inner join perusahaan_pasien inner join kecamatan inner join kabupaten" +
                    " on reg_periksa.no_rkm_medis=pasien.no_rkm_medis and reg_periksa.kd_dokter=dokter.kd_dokter and pasien.kd_kel=kelurahan.kd_kel "+
                    "and pasien.perusahaan_pasien=perusahaan_pasien.kode_perusahaan and pasien.kd_kec=kecamatan.kd_kec and pasien.kd_kab=kabupaten.kd_kab "+
                    "where reg_periksa.no_rawat='"+TNoRw.getText()+"' ",param);
                this.setCursor(Cursor.getDefaultCursor());
            }else if (tbDokter.getValueAt(tbDokter.getSelectedRow(),9).toString().equals("Surat Cuti Melahirkan")){
                     this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                     param.put("TanggalPerkiraan",TanggalPerkiraan.getSelectedItem().toString());
                    param.put("nosakit",NoSurat.getText());
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    param.put("dpjp",Sequel.cariIsi("select d.nm_dokter from reg_periksa  rp inner join dokter d on d.kd_dokter=rp.kd_dokter where rp.no_rawat='"+TNoRw.getText()+"' "));
                    param.put("logo",Sequel.cariGambar("select setting.logo from setting"));
                Valid.MyReportqry("rptCutiMelahirkankunh.jasper","report","::[ Surat Cuti Melahirkan ]::",
                    "select DATE_FORMAT(reg_periksa.tgl_registrasi,'%dd-%mm-%YYYY')as tgl_registrasi,perusahaan_pasien.nama_perusahaan,reg_periksa.no_rawat,dokter.nm_dokter,pasien.keluarga,pasien.namakeluarga,pasien.tgl_lahir,pasien.jk," +
                    " pasien.nm_pasien,concat(reg_periksa.umurdaftar,' ',reg_periksa.sttsumur)as umur,pasien.pekerjaan,concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) as alamat, dokter.no_ijn_praktek,m_surat_kunh.assesmen,m_surat_kunh.keterangan" +
                    " from reg_periksa inner join pasien inner join dokter inner join kelurahan inner join perusahaan_pasien inner join kecamatan inner join kabupaten inner join m_surat_kunh" +
                    " on reg_periksa.no_rkm_medis=pasien.no_rkm_medis and reg_periksa.kd_dokter=dokter.kd_dokter and pasien.kd_kel=kelurahan.kd_kel "+
                    "and pasien.perusahaan_pasien=perusahaan_pasien.kode_perusahaan and pasien.kd_kec=kecamatan.kd_kec and pasien.kd_kab=kabupaten.kd_kab and reg_periksa.no_rawat=m_surat_kunh.no_rawat "+
                    "where reg_periksa.no_rawat='"+TNoRw.getText()+"' and m_surat_kunh.no_surat='"+NoSurat.getText()+"' ",param);
                this.setCursor(Cursor.getDefaultCursor());
            }else if (tbDokter.getValueAt(tbDokter.getSelectedRow(),9).toString().equals("Surat Terbang")){
                     this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();    
                    param.put("nosakit",NoSurat.getText());
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    param.put("dpjp",Sequel.cariIsi("select d.nm_dokter from reg_periksa  rp inner join dokter d on d.kd_dokter=rp.kd_dokter where rp.no_rawat='"+TNoRw.getText()+"' "));
                    param.put("logo",Sequel.cariGambar("select setting.logo from setting"));
                Valid.MyReportqry("rptSuratTerbangkunh.jasper","report","::[ Surat Terbang ]::",
                    "select DATE_FORMAT(reg_periksa.tgl_registrasi,'%dd-%mm-%YYYY')as tgl_registrasi,perusahaan_pasien.nama_perusahaan,reg_periksa.no_rawat,dokter.nm_dokter,pasien.keluarga,pasien.namakeluarga,pasien.tgl_lahir,pasien.jk," +
                    " pasien.nm_pasien,concat(reg_periksa.umurdaftar,' ',reg_periksa.sttsumur)as umur,pasien.pekerjaan,concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) as alamat, dokter.no_ijn_praktek,m_surat_kunh.assesmen,m_surat_kunh.keterangan" +
                    " from reg_periksa inner join pasien inner join dokter inner join kelurahan inner join perusahaan_pasien inner join kecamatan inner join kabupaten inner join m_surat_kunh" +
                    " on reg_periksa.no_rkm_medis=pasien.no_rkm_medis and reg_periksa.kd_dokter=dokter.kd_dokter and pasien.kd_kel=kelurahan.kd_kel "+
                    "and pasien.perusahaan_pasien=perusahaan_pasien.kode_perusahaan and pasien.kd_kec=kecamatan.kd_kec and pasien.kd_kab=kabupaten.kd_kab and reg_periksa.no_rawat=m_surat_kunh.no_rawat "+
                    "where reg_periksa.no_rawat='"+TNoRw.getText()+"' and m_surat_kunh.no_surat='"+NoSurat.getText()+"' ",param);
                this.setCursor(Cursor.getDefaultCursor());
            }
        }
    }//GEN-LAST:event_MnCetakSuratActionPerformed

    private void AssementCutiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AssementCutiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssementCutiKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSuratKUNH dialog = new DlgSuratKUNH(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextArea Assement;
    private widget.TextArea AssementCuti;
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpanSuratCuti;
    private widget.Button BtnSimpanSuratSakit;
    private widget.Button BtnSimpanSuratTerbang;
    private widget.CekBox ChkInput;
    private widget.Tanggal DTPCari1;
    private widget.Tanggal DTPCari2;
    private widget.PanelBiasa FormInput;
    private widget.TextArea KetCutiMelahirkan;
    private widget.TextArea KetSuratTerbang;
    private widget.Label LCount;
    private widget.TextBox LamaSakit;
    private javax.swing.JMenuItem MnCetakSurat;
    private widget.TextBox NoSurat;
    private javax.swing.JPanel PanelInput;
    private widget.TextBox TCari;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRm;
    private widget.TextBox TNoRw;
    private widget.TextBox TPasien;
    private widget.Tanggal TanggalAkhir;
    private widget.Tanggal TanggalAwal;
    private widget.Tanggal TanggalPerkiraan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel13;
    private widget.Label jLabel14;
    private widget.Label jLabel15;
    private widget.Label jLabel16;
    private widget.Label jLabel18;
    private widget.Label jLabel19;
    private widget.Label jLabel21;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private widget.Label label10;
    private widget.Label label40;
    private widget.Label label41;
    private widget.Label label42;
    private widget.Label label43;
    private widget.Label label44;
    private widget.Label label45;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.panelisi panelisi2;
    private widget.ScrollPane scrollPane1;
    private widget.ScrollPane scrollPane17;
    private widget.ScrollPane scrollPane18;
    private widget.ScrollPane scrollPane19;
    private widget.ScrollPane scrollPane20;
    private widget.Table tbDokter;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        Valid.tabelKosong(tabMode);
        try{
            ps=koneksi.prepareStatement( "select s.no_surat,s.no_rawat,rp.no_rkm_medis,p.nm_pasien," +
                    " s.tanggalawal,s.tanggalakhir,s.lamasakit,s.assesmen,s.keterangan,s.jenis" +
                    " from m_surat_kunh s inner join reg_periksa rp on s.no_rawat=rp.no_rawat" +
                    " inner join pasien p on rp.no_rkm_medis=p.no_rkm_medis "+
                    " WHERE s.tanggalawal between ? and ? and s.no_surat like '%"+TCari.getText().trim()+"%' or "+
                    " s.tanggalawal between ? and ? and s.no_rawat like '%"+TCari.getText().trim()+"%' or "+
                    " s.tanggalawal between ? and ? and rp.no_rkm_medis like '%"+TCari.getText().trim()+"%' or "+
                    " s.tanggalawal between ? and ? and p.nm_pasien like '%"+TCari.getText().trim()+"%' or "+
                    " s.tanggalawal between ? and ? and s.jenis like '%"+TCari.getText().trim()+"%' "+
                     "order by s.no_surat");
            try {
                ps.setString(1,Valid.SetTgl(DTPCari1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(DTPCari2.getSelectedItem()+""));
                ps.setString(3,Valid.SetTgl(DTPCari1.getSelectedItem()+""));
                ps.setString(4,Valid.SetTgl(DTPCari2.getSelectedItem()+""));
                ps.setString(5,Valid.SetTgl(DTPCari1.getSelectedItem()+""));
                ps.setString(6,Valid.SetTgl(DTPCari2.getSelectedItem()+""));
                ps.setString(7,Valid.SetTgl(DTPCari1.getSelectedItem()+""));
                ps.setString(8,Valid.SetTgl(DTPCari2.getSelectedItem()+""));
                ps.setString(9,Valid.SetTgl(DTPCari1.getSelectedItem()+""));
                ps.setString(10,Valid.SetTgl(DTPCari2.getSelectedItem()+""));
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new Object[]{rs.getString(1),
                                   rs.getString(2),
                                   rs.getString(3),
                                   rs.getString(4),
                                   rs.getString(5),
                                   rs.getString(6),
                                   rs.getString(7),
                                   rs.getString(8),
                                   rs.getString(9),
                                   rs.getString(10)
                    });
                }
            } catch (Exception e) {
                System.out.println(e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        LCount.setText(""+tabMode.getRowCount());
    }

    public void emptTeks() {
        TNoRw.setText("");
        TNoRm.setText("");
        TPasien.setText("");
        TanggalAwal.setDate(new Date());
        TanggalAkhir.setDate(new Date());
        TanggalPerkiraan.setDate(new Date());
        KetCutiMelahirkan.setText("KEPERLUAN CUTI MELAHIRKAN");
        KetSuratTerbang.setText("BERPERGIAN DENGAN PESAWAT TERBANG");
        Assement.setText(Sequel.cariIsi("select penilaian from pemeriksaan_ralan where no_rawat='"+TNoRw.getText()+"' "));
        AssementCuti.setText(Sequel.cariIsi("select penilaian from pemeriksaan_ralan where no_rawat='"+TNoRw.getText()+"' "));
        LamaSakit.setText("");
        autoNomorSurat();
 
    }

    private void getData() {
        if(tbDokter.getSelectedRow()!= -1){
            NoSurat.setText(tbDokter.getValueAt(tbDokter.getSelectedRow(),0).toString());
            TNoRw.setText(tbDokter.getValueAt(tbDokter.getSelectedRow(),1).toString());
            TNoRm.setText(tbDokter.getValueAt(tbDokter.getSelectedRow(),2).toString());
            TPasien.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),3).toString());
            Valid.SetTgl(TanggalAwal,tbDokter.getValueAt(tbDokter.getSelectedRow(),4).toString());
            Valid.SetTgl(TanggalAkhir,tbDokter.getValueAt(tbDokter.getSelectedRow(),5).toString());
            Valid.SetTgl(TanggalPerkiraan,tbDokter.getValueAt(tbDokter.getSelectedRow(),5).toString());
            LamaSakit.setText(tbDokter.getValueAt(tbDokter.getSelectedRow(),6).toString());                     
            if(tbDokter.getValueAt(tbDokter.getSelectedRow(),9).toString().equals("Surat Sakit")){
                Valid.SetTgl(TanggalAkhir,tbDokter.getValueAt(tbDokter.getSelectedRow(),5).toString());
                TanggalPerkiraan.setDate(new Date());
                AssementCuti.setText("");
                KetCutiMelahirkan.setText("");
                Assement.setText("");
                KetSuratTerbang.setText("");
            }else if (tbDokter.getValueAt(tbDokter.getSelectedRow(),9).toString().equals("Surat Cuti Melahirkan")){
                Valid.SetTgl(TanggalPerkiraan,tbDokter.getValueAt(tbDokter.getSelectedRow(),5).toString());
                TanggalAkhir.setDate(new Date());
                KetCutiMelahirkan.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),8).toString());
                 AssementCuti.setText(tbDokter.getValueAt(tbDokter.getSelectedRow(),7).toString()); 
                 Assement.setText("");
                KetSuratTerbang.setText("");        
            }else if (tbDokter.getValueAt(tbDokter.getSelectedRow(),9).toString().equals("Surat Terbang")){
                TanggalAwal.setDate(new Date());
                TanggalAkhir.setDate(new Date());
                TanggalPerkiraan.setDate(new Date());
                KetSuratTerbang.setText(tabMode.getValueAt(tbDokter.getSelectedRow(),8).toString());
                KetCutiMelahirkan.setText("");
                Assement.setText(tbDokter.getValueAt(tbDokter.getSelectedRow(),7).toString()); 
                AssementCuti.setText("");
            }
          
        }   
    }

    public JTable getTable(){
        return tbDokter;
    }
    
      private void isRawat() {
         Sequel.cariIsi("select reg_periksa.no_rkm_medis from reg_periksa where reg_periksa.no_rawat='"+TNoRw.getText()+"' ",TNoRM);
    }

    private void isPsien() {
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis='"+TNoRM.getText()+"' ",TPasien);
    }
    
    public void setNoRm(String norwt, Date tgl1, Date tgl2) {
        TNoRw.setText(norwt);
        TCari.setText(norwt);
        TanggalAwal.setDate(tgl1);
        TanggalAkhir.setDate(tgl2);
        isRawat();
        isPsien(); 
        ChkInput.setSelected(true);
        isForm();
        Assement.setText(Sequel.cariIsi("select penilaian from pemeriksaan_ralan where no_rawat='"+TNoRw.getText()+"' "));
        AssementCuti.setText(Sequel.cariIsi("select penilaian from pemeriksaan_ralan where no_rawat='"+TNoRw.getText()+"' "));
    }
    
    private void isForm(){
        if(ChkInput.isSelected()==true){
            ChkInput.setVisible(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH,220));
            FormInput.setVisible(true);      
            ChkInput.setVisible(true);
        }else if(ChkInput.isSelected()==false){           
            ChkInput.setVisible(false);            
            PanelInput.setPreferredSize(new Dimension(WIDTH,20));
            FormInput.setVisible(false);      
            ChkInput.setVisible(true);
        }
    }    
    
     private void autoNomorSurat(){
     Valid.autoNomerSurat("select ifnull(MAX(CONVERT(LEFT(m_surat_kunh.no_surat,3),signed)),0) from m_surat_kunh where m_surat_kunh.tanggalawal like '%"+Valid.SetTgl(TanggalAwal.getSelectedItem()+"").substring(0, 7)+"%' ",
                "/KUNH/"+ Valid.SetTgl(TanggalAwal.getSelectedItem() + "").substring(5, 7)
                + "/" + Valid.SetTgl(TanggalAwal.getSelectedItem() + "").substring(0, 4), 3, NoSurat);
        NoSurat.requestFocus();
    
    }
 
}
