/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package antrian;

//import custom.*;
//import bpjsvclaim.BPJSApi;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.akses;
import simrskhanza.*;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.awt.Dimension;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import inventory.DlgCariKonversi;
import inventory.DlgCariObat;
import inventory.DlgCariObat2;
import inventory.DlgCariObat3;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.Timer;
import kepegawaian.DlgCariDokter;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author perpustakaan
 */
public class DlgCallerAntrianApotek extends javax.swing.JDialog {
  private sekuel Sequel=new sekuel();
  private validasi Valid=new validasi();
  private Connection koneksi=koneksiDB.condb();
  public static int PoliClient;
  private int i=0;
  private static final Properties LoketId = new Properties();
  private DlgCariDokter dokter=new DlgCariDokter(null,false);
  private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
  
  public DlgCallerAntrianApotek(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tampilSisa();
//        Jumlah.setText(Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='dokter' and client='"+akses.getkode()+"'"));
//        SisaAntrian.setText(Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='dokter' and client='"+akses.getkode()+"' and status='Pending' "));
//        jNoAntrian.setText(Sequel.cariIsi("SELECT queue_number FROM tt_queue WHERE type='dokter' and client='"+akses.getkode()+"' and status='Closed' ORDER BY id DESC LIMIT 1 "));
        this.setLocation(8,1);
        setSize(950,350);
//        try {
//            LoketId.loadFromXML(new FileInputStream("setting/loketid.xml"));
//        } catch (Exception e) {
//            System.out.println("Notif Setting : "+e);
//        }
//        LoketClient = Integer.parseInt(LoketId.getProperty("LOKETID"));
//        CmbLoket.setSelectedIndex(LoketClient-1);
//        KodeDokter.getText(PoliClient-1);
//        System.out.println("Notif : "+jNoAntrian);
//        System.out.println("Notif : "+jSisa);
        
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        FormInput1 = new widget.PanelBiasa();
        jNoAntrian = new widget.Label();
        BtnRecall = new widget.Button();
        BtnCalled = new widget.Button();
        label14 = new widget.Label();
        FormInput3 = new widget.PanelBiasa();
        Jumlah = new widget.Label();
        FormInput4 = new widget.PanelBiasa();
        SisaAntrian = new widget.Label();
        CmbKategori = new widget.ComboBox();
        panelGlass8 = new widget.panelisi();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "::[ Farmacy Caller ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(70, 70, 70))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(950, 200));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput.setLayout(null);

        FormInput1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "No. Antrian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        FormInput1.setName("FormInput1"); // NOI18N
        FormInput1.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput1.setLayout(null);

        jNoAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNoAntrian.setText("-");
        jNoAntrian.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jNoAntrian.setName("jNoAntrian"); // NOI18N
        FormInput1.add(jNoAntrian);
        jNoAntrian.setBounds(15, 20, 310, 110);

        FormInput.add(FormInput1);
        FormInput1.setBounds(50, 10, 350, 150);

        BtnRecall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnRecall.setMnemonic('T');
        BtnRecall.setText(" Re-Called ");
        BtnRecall.setToolTipText("Alt+T");
        BtnRecall.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnRecall.setName("BtnRecall"); // NOI18N
        BtnRecall.setPreferredSize(new java.awt.Dimension(200, 30));
        BtnRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecallActionPerformed(evt);
            }
        });
        BtnRecall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnRecallKeyPressed(evt);
            }
        });
        FormInput.add(BtnRecall);
        BtnRecall.setBounds(440, 160, 180, 50);

        BtnCalled.setBackground(new java.awt.Color(0, 204, 153));
        BtnCalled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/History.png"))); // NOI18N
        BtnCalled.setMnemonic('T');
        BtnCalled.setText(" Called");
        BtnCalled.setToolTipText("Alt+T");
        BtnCalled.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnCalled.setName("BtnCalled"); // NOI18N
        BtnCalled.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnCalled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalledActionPerformed(evt);
            }
        });
        BtnCalled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCalledKeyPressed(evt);
            }
        });
        FormInput.add(BtnCalled);
        BtnCalled.setBounds(250, 160, 170, 50);

        label14.setText("Kategori :");
        label14.setName("label14"); // NOI18N
        label14.setPreferredSize(new java.awt.Dimension(70, 23));
        FormInput.add(label14);
        label14.setBounds(10, 200, 60, 23);

        FormInput3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Antrian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        FormInput3.setName("FormInput3"); // NOI18N
        FormInput3.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput3.setLayout(null);

        Jumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jumlah.setText("-");
        Jumlah.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        Jumlah.setName("Jumlah"); // NOI18N
        FormInput3.add(Jumlah);
        Jumlah.setBounds(15, 20, 180, 110);

        FormInput.add(FormInput3);
        FormInput3.setBounds(410, 10, 210, 150);

        FormInput4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sisa Antrian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        FormInput4.setName("FormInput4"); // NOI18N
        FormInput4.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput4.setLayout(null);

        SisaAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SisaAntrian.setText("-");
        SisaAntrian.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        SisaAntrian.setName("SisaAntrian"); // NOI18N
        FormInput4.add(SisaAntrian);
        SisaAntrian.setBounds(15, 20, 180, 110);

        FormInput.add(FormInput4);
        FormInput4.setBounds(630, 10, 210, 150);

        CmbKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TNI", "BPJS", "ASK", "UMUM" }));
        CmbKategori.setName("CmbKategori"); // NOI18N
        CmbKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbKategoriItemStateChanged(evt);
            }
        });
        CmbKategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbKategoriKeyPressed(evt);
            }
        });
        FormInput.add(CmbKategori);
        CmbKategori.setBounds(97, 200, 170, 23);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(100, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void berhasilSimpan() {  
   
} 
    
    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
    }//GEN-LAST:event_formWindowActivated

    private void BtnRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecallActionPerformed
        Sequel.queryu2("update tt_queue_farmacy set status='Open' WHERE  no_antrian='"+jNoAntrian.getText()+"' and date(datetime)='"+dateFormat.format(new Date())+"' and category='"+CmbKategori.getSelectedItem().toString()+"'");
    }//GEN-LAST:event_BtnRecallActionPerformed

    private void BtnRecallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnRecallKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRecallKeyPressed

    private void BtnCalledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalledActionPerformed
       // update tt_queue set status='open' WHERE type='loket' and client='1' and status='pending' ORDER BY id ASC LIMIT 1
       String sisa = Sequel.cariIsi("SELECT count(no_antrian) FROM tt_queue_farmacy WHERE date(datetime)='"+dateFormat.format(new Date())+"' and status='Pending' and category='"+CmbKategori.getSelectedItem().toString()+"'");
       if(sisa.equals("0")){
            JOptionPane.showMessageDialog(null,"Maaf, data Antrian sudah habis.");
                  
       }else{
        Sequel.queryu2("update tt_queue_farmacy set status='Open' WHERE date(datetime)='"+dateFormat.format(new Date())+"' and status='Pending' and category='"+CmbKategori.getSelectedItem().toString()+"'  ORDER BY id ASC LIMIT 1");
        Jumlah.setText(Sequel.cariIsi("SELECT count(no_antrian) FROM tt_queue_farmacy WHERE  date(datetime)='"+dateFormat.format(new Date())+"' and category='"+CmbKategori.getSelectedItem().toString()+"'"));
        SisaAntrian.setText(Sequel.cariIsi("SELECT count(no_antrian) FROM tt_queue_farmacy WHERE  status='Pending' and date(datetime)='"+dateFormat.format(new Date())+"' and category='"+CmbKategori.getSelectedItem().toString()+"'"));
        jNoAntrian.setText(Sequel.cariIsi("SELECT no_antrian FROM tt_queue_farmacy WHERE  status='Open' and date(datetime)='"+dateFormat.format(new Date())+"' and category='"+CmbKategori.getSelectedItem().toString()+"' ORDER BY id DESC LIMIT 1 "));
       }        
    }//GEN-LAST:event_BtnCalledActionPerformed
private void tampilSisa(){
        Jumlah.setText(Sequel.cariIsi("SELECT count(category) FROM tt_queue_farmacy WHERE date(datetime)='"+dateFormat.format(new Date())+"' and category='"+CmbKategori.getSelectedItem().toString()+"'"));
        SisaAntrian.setText(Sequel.cariIsi("SELECT count(category) FROM tt_queue_farmacy WHERE date(datetime)='"+dateFormat.format(new Date())+"' and status='Pending' and category='"+CmbKategori.getSelectedItem().toString()+"'"));
        jNoAntrian.setText(Sequel.cariIsi("SELECT no_antrian FROM tt_queue_farmacy WHERE date(datetime)='"+dateFormat.format(new Date())+"' and status='Closed' and category='"+CmbKategori.getSelectedItem().toString()+"' ORDER BY id DESC LIMIT 1 ")); 
}
    private void BtnCalledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCalledKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCalledKeyPressed

    private void CmbKategoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbKategoriKeyPressed

    }//GEN-LAST:event_CmbKategoriKeyPressed

    private void CmbKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbKategoriItemStateChanged
       tampilSisa();
    }//GEN-LAST:event_CmbKategoriItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCallerAntrianApotek dialog = new DlgCallerAntrianApotek(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCalled;
    private widget.Button BtnKeluar;
    private widget.Button BtnRecall;
    private widget.ComboBox CmbKategori;
    private widget.PanelBiasa FormInput;
    private widget.PanelBiasa FormInput1;
    private widget.PanelBiasa FormInput3;
    private widget.PanelBiasa FormInput4;
    private widget.Label Jumlah;
    private widget.Label SisaAntrian;
    private widget.InternalFrame internalFrame1;
    private widget.Label jNoAntrian;
    private widget.Label label14;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
//        Sequel.cariIsi("select nm_pasien from pasien where no_rkm_medis=? ",TPasien,TNoRM.getText());
    }

   

}
