/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPerawatan.java
 *
 * Created on May 23, 2010, 6:36:30 PM
 */

package modifikasi;

import bridging.ApiWA;
import bridging.ApiWAMEDIA;
import fungsi.WarnaTable;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author dosen
 */
public final class DlgwhatsappHasilRad extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private HttpHeaders headers;
    private HttpEntity requestEntity;
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private ApiWA api=new ApiWA();
    private ApiWAMEDIA api_media=new ApiWAMEDIA();
    private FileWriter file1;
    private int i=0;
    private String uri="", Nohp="",file="",uri1="",tanggal="",jam="",token="",stringbalik="Hallo, Selamat ",respon="", requestJson,requestJson1, URL_media="",URL="",URL_MEDIA="",catat="",rsk="",poli="",antrian="", tgl="",
            isi="Yang terhormat #nama# dengan Nomor Rekam Medik #norm# Berikut Kami Kirimkan Hasil Pemeriksaan Radiologi Anda. Pesan WhatsApp ini dikirim otomatis oleh #rs#  Terima Kasih";
    

    /** Creates new form DlgPerawatan
     * @param parent
     * @param modal */
    public DlgwhatsappHasilRad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        token    = Sequel.cariIsi("SELECT api_key FROM settingwa where keterangan='radiologi' ");
        URL      = Sequel.cariIsi("SELECT urlwa FROM settingwa where keterangan='radiologi'");
        Nohp     = Sequel.cariIsi("SELECT nohprs FROM settingwa where keterangan='radiologi'");
        URL_MEDIA= Sequel.cariIsi("SELECT urlwamedia FROM settingwa where keterangan='radiologi'");
        uri="http://"+koneksiDB.HOSTHYBRIDWEB()+":"+koneksiDB.PORTWEB()+"/"+koneksiDB.HYBRIDWEB()+"/radiologi";
        uri1=koneksiDB.HYBRIDWEB();
        this.setLocation(8,1);
        setSize(885,674);
        
        Object[] row={"Pemeriksaan","Hasil","Satuan","Nilai Rujukan","Keterangan","ID Detail","Kode Periksa"};
        tabMode=new DefaultTableModel(null,row){
             @Override public boolean isCellEditable(int rowIndex, int colIndex){
                    boolean a = false;
                    if ((colIndex==1)||(colIndex==3)||(colIndex==4)) {
                        a=true;
                    }
                    return a;
             }
             Class[] types = new Class[] {
                java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class
             };
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }              
        };
        
        //tbPemeriksaan.setModel(tabMode);
        //tampilPr();

        //tbPemeriksaan.setPreferredScrollableViewportSize(new Dimension(500,500));
        //tbPemeriksaan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass8 = new widget.panelisi();
        BtnKirimWA = new widget.Button();
        jLabel10 = new widget.Label();
        BtnKeluar = new widget.Button();
        panelGlass11 = new widget.panelisi();
        jLabel3 = new widget.Label();
        TNoRw = new widget.TextBox();
        TNoRM = new widget.TextBox();
        TPasien = new widget.TextBox();
        TNoWA = new widget.TextBox();
        TUrl = new widget.TextBox();
        jLabel4 = new widget.Label();
        jLabel5 = new widget.Label();
        jLabel6 = new widget.Label();
        TCatatan = new widget.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Kirim Hasil Radiologi Via WhatsApp ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setMinimumSize(new java.awt.Dimension(50, 71));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKirimWA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/34.png"))); // NOI18N
        BtnKirimWA.setMnemonic('K');
        BtnKirimWA.setText("Kirim WA");
        BtnKirimWA.setToolTipText("Alt+K");
        BtnKirimWA.setName("BtnKirimWA"); // NOI18N
        BtnKirimWA.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKirimWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimWAActionPerformed(evt);
            }
        });
        BtnKirimWA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKirimWAKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKirimWA);

        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(400, 30));
        panelGlass8.add(jLabel10);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        panelGlass11.setName("panelGlass11"); // NOI18N
        panelGlass11.setPreferredSize(new java.awt.Dimension(44, 73));
        panelGlass11.setLayout(null);

        jLabel3.setText("Pesan:");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass11.add(jLabel3);
        jLabel3.setBounds(0, 110, 100, 23);

        TNoRw.setEditable(false);
        TNoRw.setHighlighter(null);
        TNoRw.setName("TNoRw"); // NOI18N
        TNoRw.setPreferredSize(new java.awt.Dimension(130, 23));
        panelGlass11.add(TNoRw);
        TNoRw.setBounds(110, 10, 130, 23);

        TNoRM.setEditable(false);
        TNoRM.setHighlighter(null);
        TNoRM.setName("TNoRM"); // NOI18N
        TNoRM.setPreferredSize(new java.awt.Dimension(100, 23));
        panelGlass11.add(TNoRM);
        TNoRM.setBounds(250, 10, 100, 23);

        TPasien.setEditable(false);
        TPasien.setHighlighter(null);
        TPasien.setName("TPasien"); // NOI18N
        TPasien.setPreferredSize(new java.awt.Dimension(290, 23));
        panelGlass11.add(TPasien);
        TPasien.setBounds(360, 10, 290, 23);

        TNoWA.setHighlighter(null);
        TNoWA.setName("TNoWA"); // NOI18N
        TNoWA.setPreferredSize(new java.awt.Dimension(100, 23));
        panelGlass11.add(TNoWA);
        TNoWA.setBounds(110, 40, 150, 23);

        TUrl.setHighlighter(null);
        TUrl.setName("TUrl"); // NOI18N
        TUrl.setPreferredSize(new java.awt.Dimension(100, 23));
        panelGlass11.add(TUrl);
        TUrl.setBounds(110, 70, 320, 23);

        jLabel4.setText("No.Rawat :");
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass11.add(jLabel4);
        jLabel4.setBounds(0, 10, 100, 23);

        jLabel5.setText("No.WhatsApp:");
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass11.add(jLabel5);
        jLabel5.setBounds(0, 40, 100, 23);

        jLabel6.setText("Lokasi Berkas:");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass11.add(jLabel6);
        jLabel6.setBounds(0, 70, 100, 23);

        TCatatan.setColumns(40);
        TCatatan.setRows(5);
        TCatatan.setName("TCatatan"); // NOI18N
        panelGlass11.add(TCatatan);
        TCatatan.setBounds(110, 110, 370, 230);

        internalFrame1.add(panelGlass11, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKirimWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimWAActionPerformed
        
        if(TNoRM.getText().trim().equals("")||TPasien.getText().trim().equals("")){
            Valid.textKosong(TNoRM,"No.Rekam Medis");
        }else if(TNoWA.getText().trim().equals("")){
            Valid.textKosong(TNoWA,"No Whats App");
        }else if(TUrl.getText().trim().equals("")){
            Valid.textKosong(TUrl,"Lokasi berkas"); 
        }else if(TCatatan.getText().trim().equals("")){
            Valid.textKosong(TCatatan,"Pesan");
        }else if (Sequel.cariInteger("select count(gambar_radiologi.lokasi_gambar) from gambar_radiologi inner join periksa_radiologi on periksa_radiologi.no_rawat=gambar_radiologi.no_rawat AND periksa_radiologi.tgl_periksa=gambar_radiologi.tgl_periksa AND periksa_radiologi.jam=gambar_radiologi.jam where gambar_radiologi.no_rawat='"+TNoRw.getText()+"' AND gambar_radiologi.tgl_periksa='"+tanggal+"' AND gambar_radiologi.jam='"+jam+"' AND lokasi_gambar LIKE '%jpeg%' ")>=1)        
             {
            //------------------------------kirim ke WA API------------------>
             try{   
    
                headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.add("Content-Type","application/json;charset=UTF-8");
                //headers.add("sender",api.getHmac());
                 requestJson ="{\"api_key\":\""+token+"\", "+
                              "{\"sender\":\""+Nohp+"\", "+
                              "\"number\":\""+TNoWA.getText()+"\","+ 
                              "\"message\":\""+TCatatan.getText()+"\""+
                              "}";
                 System.out.println("Kirim WA VIA JSON : "+requestJson);
                 requestEntity = new HttpEntity(requestJson,headers);
                 requestJson=api.getRest().exchange(URL, HttpMethod.POST, requestEntity, String.class).getBody();
                
                 System.out.println("Kirim WA VIA JSON : "+requestJson);
                 requestEntity = new HttpEntity(requestJson,headers);
                 requestJson=api.getRest().exchange(URL, HttpMethod.POST, requestEntity, String.class).getBody();
                 System.out.println("respon WHATSAPP-API SERVER : "+requestJson);
                 
                }catch (Exception ex) {
                System.out.println("Notifikasi Bridging : "+ex);
                
                if(ex.toString().contains("UnknownHostException")){
                    JOptionPane.showMessageDialog(null,"Koneksi ke server WHATSAPP-API terputus...!");
               }else if(ex.toString().contains("404")){
                    JOptionPane.showMessageDialog(null,"Server Not Found. lelah bang...!");
                }else if(ex.toString().contains("502")){
                    JOptionPane.showMessageDialog(null,"Connection timed out. Hayati lelah bang...!");
                }else{
                    JOptionPane.showMessageDialog(null,respon);
                }
            } 
             
           try{   
      
                headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.add("Content-Type","application/json;charset=UTF-8");
                //headers.add("sender",api.getHmac());
                 requestJson1 ="{\"api_key\":\""+token+"\", "+
                               "{\"sender\":\""+Nohp+"\", "+
                              "\"number\":\""+TNoWA.getText()+"\","+ 
                              "\"media_type\":\"image\","+ 
                              "\"caption\":\""+"gambar"+"\","+
                              "\"file\":\""+uri+"/"+TUrl.getText()+"\""+
                              "}";
                 System.out.println("Kirim WA VIA JSON : "+requestJson1);
                 requestEntity = new HttpEntity(requestJson1,headers);
                 requestJson1=api_media.getRest().exchange(URL_media, HttpMethod.POST, requestEntity, String.class).getBody();
                 System.out.println("respon WHATSAPP-API SERVER : "+requestJson1);
                 
                }catch (Exception ex) {
                System.out.println("Notifikasi Bridging : "+ex);
                
                if(ex.toString().contains("UnknownHostException")){
                    JOptionPane.showMessageDialog(null,"Koneksi ke server WHATSAPP-API terputus...!");
               }else if(ex.toString().contains("404")){
                    JOptionPane.showMessageDialog(null,"Server Not Found. lelah bang...!");
                }else if(ex.toString().contains("502")){
                    JOptionPane.showMessageDialog(null,"Connection timed out. Hayati lelah bang...!");
                }else{
                    JOptionPane.showMessageDialog(null,respon);
                }
            }
            //---------------------Akhir Kirim WA ---------------------------------->
            
            //Sequel.menyimpan3("catatan_wa","?,?",2,new String[]{TNoRM.getText(),TCatatan.getText()},"no_rkm_medis=?","catatan=?",2,new String[]{TCatatan.getText(),TNoRM.getText()});  
           
        }else if (Sequel.cariInteger("select count(gambar_radiologi.lokasi_gambar) from gambar_radiologi inner join periksa_radiologi on periksa_radiologi.no_rawat=gambar_radiologi.no_rawat AND periksa_radiologi.tgl_periksa=gambar_radiologi.tgl_periksa AND periksa_radiologi.jam=gambar_radiologi.jam where gambar_radiologi.no_rawat='"+TNoRw.getText()+"' AND gambar_radiologi.tgl_periksa='"+tanggal+"' AND gambar_radiologi.jam='"+jam+"' AND lokasi_gambar LIKE '%jpg%' ")>=1)        
             {
            //------------------------------kirim ke WA API------------------>
            try{   
    
                headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.add("Content-Type","application/json;charset=UTF-8");
                //headers.add("sender",api.getHmac());
                 requestJson ="{\"api_key\":\""+token+"\", "+
                              "{\"sender\":\""+Nohp+"\", "+
                              "\"number\":\""+TNoWA.getText()+"\","+ 
                              "\"message\":\""+TCatatan.getText()+"\""+
                              "}";
                 System.out.println("Kirim WA VIA JSON : "+requestJson);
                 requestEntity = new HttpEntity(requestJson,headers);
                 requestJson=api.getRest().exchange(URL, HttpMethod.POST, requestEntity, String.class).getBody();
                
                 System.out.println("Kirim WA VIA JSON : "+requestJson);
                 requestEntity = new HttpEntity(requestJson,headers);
                 requestJson=api.getRest().exchange(URL, HttpMethod.POST, requestEntity, String.class).getBody();
                 System.out.println("respon WHATSAPP-API SERVER : "+requestJson);
                 
                }catch (Exception ex) {
                System.out.println("Notifikasi Bridging : "+ex);
                
                if(ex.toString().contains("UnknownHostException")){
                    JOptionPane.showMessageDialog(null,"Koneksi ke server WHATSAPP-API terputus...!");
               }else if(ex.toString().contains("404")){
                    JOptionPane.showMessageDialog(null,"Server Not Found. lelah bang...!");
                }else if(ex.toString().contains("502")){
                    JOptionPane.showMessageDialog(null,"Connection timed out. Hayati lelah bang...!");
                }else{
                    JOptionPane.showMessageDialog(null,respon);
                }
            } 
             
           try{   
      
                headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.add("Content-Type","application/json;charset=UTF-8");
                //headers.add("sender",api.getHmac());
                 requestJson1 ="{\"api_key\":\""+token+"\", "+
                              "{\"sender\":\""+Nohp+"\", "+
                              "\"number\":\""+TNoWA.getText()+"\","+
                              "\"media_type\":\"image\","+ 
                              "\"caption\":\""+"gambar"+"\","+
                              "\"file\":\""+uri+"/"+TUrl.getText()+"\""+
                              "}";
                 System.out.println("Kirim WA VIA JSON : "+requestJson1);
                 requestEntity = new HttpEntity(requestJson1,headers);
                 requestJson1=api_media.getRest().exchange(URL_media, HttpMethod.POST, requestEntity, String.class).getBody();
                 System.out.println("respon WHATSAPP-API SERVER : "+requestJson1);
                 
                }catch (Exception ex) {
                System.out.println("Notifikasi Bridging : "+ex);
                
                if(ex.toString().contains("UnknownHostException")){
                    JOptionPane.showMessageDialog(null,"Koneksi ke server WHATSAPP-API terputus...!");
               }else if(ex.toString().contains("404")){
                    JOptionPane.showMessageDialog(null,"Server Not Found. lelah bang...!");
                }else if(ex.toString().contains("502")){
                    JOptionPane.showMessageDialog(null,"Connection timed out. Hayati lelah bang...!");
                }else{
                    JOptionPane.showMessageDialog(null,respon);
                }
            }
            //---------------------Akhir Kirim WA ---------------------------------->
            
            //Sequel.menyimpan3("catatan_wa","?,?",2,new String[]{TNoRM.getText(),TCatatan.getText()},"no_rkm_medis=?","catatan=?",2,new String[]{TCatatan.getText(),TNoRM.getText()});
           
        }
        
       
        
        
        
       
        JOptionPane.showMessageDialog(null,"Proses update hasil pemeriksaan sudah selesai !!!");
        dispose();
        //ChkJln.setSelected(true);
}//GEN-LAST:event_BtnKirimWAActionPerformed

    private void BtnKirimWAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKirimWAKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnKirimWAActionPerformed(null);
        }else{
               //Valid.pindah(evt,Pemeriksaan,BtnHapus);
        }
}//GEN-LAST:event_BtnKirimWAKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnKirimWA,TNoRw);}
}//GEN-LAST:event_BtnKeluarKeyPressed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(() -> {
//            DlgwhatsappHasil dialog = new DlgwhatsappHasil(new javax.swing.JFrame(), true);
//            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                @Override
//                public void windowClosing(java.awt.event.WindowEvent e) {
//                    System.exit(0);
//                }
//            });
//            dialog.setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnKirimWA;
    private widget.TextArea TCatatan;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRw;
    private widget.TextBox TNoWA;
    private widget.TextBox TPasien;
    private widget.TextBox TUrl;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.panelisi panelGlass11;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

    public void setNoRm(String norwt,String tanggal,String jam) {        
        try {
            TNoRw.setText(norwt);
            Sequel.cariIsi("select no_rkm_medis from reg_periksa where no_rawat=? ",TNoRM,TNoRw.getText());
            TUrl.setText(Sequel.cariIsi("select gambar_radiologi.lokasi_gambar from gambar_radiologi inner join periksa_radiologi on periksa_radiologi.no_rawat=gambar_radiologi.no_rawat AND periksa_radiologi.tgl_periksa=gambar_radiologi.tgl_periksa AND periksa_radiologi.jam=gambar_radiologi.jam where gambar_radiologi.no_rawat='"+TNoRw.getText()+"' AND gambar_radiologi.tgl_periksa='"+tanggal+"' AND gambar_radiologi.jam='"+jam+"' "));
            //Sequel.cariIsi("select gambar_radiologi.lokasi_gambar from gambar_radiologi inner join periksa_radiologi on periksa_radiologi.no_rawat=hasil_radiologi.no_rawat AND periksa_radiologi.tgl_periksa=hasil_radiologi.jam AND periksa_radiologi.jam=hasil_radiologi.jam where hasil_radiologi.no_rawat=? AND hasil_radiologi.tgl_periksa=? AND hasil_radiologi.jam=? ",TUrl,TNoRw.getText(),tanggal,jam);
            Sequel.cariIsi("select nm_pasien from pasien where no_rkm_medis=? ",TPasien,TNoRM.getText());
            Sequel.cariIsi("select no_tlp from pasien where no_rkm_medis=? ",TNoWA,TNoRM.getText());
            rsk=Sequel.cariIsi("select nama_instansi from setting" );
            TCatatan.setText(isi.replace("#nama#",TPasien.getText()).replace("#norm#",TNoRM.getText()).replace("#rs#", rsk));
            this.tanggal=tanggal;
            this.jam=jam;
         
   
        } catch (Exception e) {
            System.out.println(e);
        }         
    }
    
//    public void isCek(){
//        BtnKirimWA.setEnabled(akses.getperiksa_labpcr());
//    }
  }
